<?php

namespace App\Http\Controllers;

use App\Models\Order;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;

class OrderController extends Controller
{
    public function index()
    {
        return view('pages.orders');
    }

    public function printAllDataOrders()
    {
        $orders = Order::with(['user', 'orderItems.product', 'payments'])->get();

        $user = auth()->user();
        $printedBy = $user ? htmlspecialchars($user->name) : 'Guest';
        $printedAt = now()->format('F j, Y \a\t g:i A');

        // Calculate totals
        $totalAmount = $orders->sum('total_amount');
        $totalPaid = $orders->sum(function($order) {
            return $order->payments->where('status', 'CONFIRMED')->sum('amount');
        });
        $totalBalance = $totalAmount - $totalPaid;

        $html = '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Orders Report | Profit Gym Tones</title>
            <link rel="icon" type="image/png" href="' . asset('images/header/favicon.png') . '">
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="' . asset('css/print.css') . '">
            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(function() {
                        window.close();
                    }, 1000);
                };
            </script>
        </head>
        <body>
            <div class="document">
                <div class="header">
                    <img src="' . asset('logos/profit-gym.png') . '" alt="Company Logo" class="header-logo">
                    <h1>PROFIT GYM TONE MANAGEMENT</h1>
                    <p>jeremiahpanganibanr@gmail.com | +63 912 123 6182</p>
                </div>

                <h2 class="report-title">ORDERS REPORT</h2>

                <table>
                    <thead>
                        <tr>
                            <th>Order ID</th>
                            <th>Customer</th>
                            <th>Total Amount</th>
                            <th>Status</th>
                            <th>Payment Method</th>
                            <th>Payment Status</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>';

        foreach ($orders as $order) {
            // Get payment information
            $payment = $order->payments->first();
            $paymentMethod = $payment ? match ($payment->payment_method) {
                'GCASH' => 'GCash',
                'OVER_THE_COUNTER' => 'Over the Counter',
                default => 'N/A',
            } : 'N/A';

            $paymentStatus = $payment ? $payment->status : 'N/A';

            $statusBadge = match ($order->status) {
                'PENDING' => '<span class="badge badge-pending">PENDING</span>',
                'FOR PICKUP' => '<span class="badge badge-for_pickup">FOR PICKUP</span>',
                'COMPLETED' => '<span class="badge badge-completed">COMPLETED</span>',
                'REJECTED' => '<span class="badge badge-rejected">REJECTED</span>',
                default => '<span class="badge">' . $order->status . '</span>',
            };

            $html .= '<tr>
                <td>' . $order->id . '</td>
                <td>' . ($order->user->name ?? 'N/A') . '</td>
                <td class="amount">₱' . number_format($order->total_amount, 2) . '</td>
                <td>' . $statusBadge . '</td>
                <td>' . $paymentMethod . '</td>
                <td>' . $paymentStatus . '</td>
                <td class="date">' . $order->created_at->format('M j, Y g:i A') . '</td>
            </tr>';
        }

        // Add summary row
        $html .= '<tr class="summary-row">
                <td colspan="2"><strong>TOTALS</strong></td>
                <td class="amount"><strong>₱' . number_format($totalAmount, 2) . '</strong></td>
                <td colspan="2"></td>
                <td><strong>Total Paid: ₱' . number_format($totalPaid, 2) . '</strong></td>
                <td><strong>Balance: ₱' . number_format($totalBalance, 2) . '</strong></td>
            </tr>';

        $html .= '</tbody>
                </table>

                <div class="footer">
                    <p>Generated by ' . $printedBy . ' on ' . $printedAt . '</p>
                    <p>Confidential Document • © ' . date('Y') . ' Profit Gym Tone Management</p>
                </div>
            </div>
        </body>
        </html>';

        return response($html);
    }
}