<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use Carbon\Carbon;

class PaymentController extends Controller
{
    public function index()
    {
        return view('pages.payments');
    }

    public function printAllDataPayment()
    {
        $payments = Payment::with(['typeable.user'])->get();

        $user = auth()->user();
        $printedBy = $user ? htmlspecialchars($user->name) : 'Guest';
        $printedAt = now()->format('F j, Y \a\t g:i A');

        // Calculate totals
        $totalAmount = $payments->sum('amount');
        $totalConfirmed = $payments->where('status', 'CONFIRMED')->sum('amount');
        $totalPending = $payments->where('status', 'PENDING')->sum('amount');

        $html = '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Payments Report | Profit Gym Tone</title>
            <link rel="icon" type="image/png" href="' . asset('images/header/favicon.png') . '">
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="' . asset('css/print.css') . '">
            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(function() {
                        window.close();
                    }, 1000);
                };
            </script>
        </head>
        <body>
            <div class="document">
                 <div class="header">
                    <img src="' . asset('logos/profit-gym.png') . '" alt="Company Logo" class="header-logo">
                    <p>jeremiahpanganibanr@gmail.com | +63 912 123 6182</p>
                </div>

                <h2 class="report-title">PAYMENTS REPORT</h2>

                <table>
                    <thead>
                        <tr>
                            <th>Payment ID</th>
                            <th>Customer</th>
                            <th>Type</th>
                            <th>Amount</th>
                            <th>Method</th>
                            <th>Reference No</th>
                            <th>Status</th>
                            <th>Payment Date</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>';

        foreach ($payments as $payment) {
            $customerName = $payment->customer_name ?? 
                          ($payment->typeable->user->name ?? 'N/A');
            
            $statusBadge = match ($payment->status) {
                'PENDING' => '<span class="badge badge-pending">PENDING</span>',
                'CONFIRMED' => '<span class="badge badge-confirmed">CONFIRMED</span>',
                'REJECTED' => '<span class="badge badge-rejected">REJECTED</span>',
                default => '<span class="badge">' . $payment->status . '</span>',
            };

            $imageHtml = $payment->image 
                ? '<img src="' . asset('storage/' . $payment->image) . '" class="payment-image">'
                : 'N/A';

            $html .= '<tr>
                <td>' . $payment->id . '</td>
                <td>' . htmlspecialchars($customerName) . '</td>
                <td>' . ucfirst(str_replace('_', ' ', $payment->type)) . '</td>
                <td class="amount">₱' . number_format($payment->amount, 2) . '</td>
                <td>' . match ($payment->payment_method) {
                    'OVER_THE_COUNTER' => 'Over the Counter',
                    'GCASH' => 'GCash',
                    default => $payment->payment_method,
                } . '</td>
                <td>' . ($payment->reference_no ?? 'N/A') . '</td>
                <td>' . $statusBadge . '</td>
                <td class="date">' . ($payment->payment_date ? Carbon::parse($payment->payment_date)->format('M j, Y') : 'N/A') . '</td>
             
            </tr>';
        }

        // Add summary row
        $html .= '<tr class="summary-row">
                <td colspan="3"><strong>TOTALS</strong></td>
                <td class="amount"><strong>₱' . number_format($totalAmount, 2) . '</strong></td>
                <td colspan="2"></td>
                <td>
                    <div>Confirmed: <strong>₱' . number_format($totalConfirmed, 2) . '</strong></div>
                    <div>Pending: <strong>₱' . number_format($totalPending, 2) . '</strong></div>
                </td>
                <td colspan="2"></td>
            </tr>';

        $html .= '</tbody>
                </table>

                <div class="footer">
                    <p>Generated by ' . $printedBy . ' on ' . $printedAt . '</p>
                    <p>Confidential Document • © ' . date('Y') . ' Profit Gym Tone Management</p>
                </div>
            </div>
        </body>
        </html>';

        return response($html);
    }
}