<?php

namespace App\Http\Controllers;

use App\Models\User;
use Carbon\Carbon;

class UserController extends Controller
{
    public function index()
    {
        return view('pages.users');
    }

    public function printAllDataUser()
    {
        $users = User::all();

        $user = auth()->user();
        $printedBy = $user ? htmlspecialchars($user->name) : 'Guest';
        $printedAt = now()->format('F j, Y \a\t g:i A');

        // Count users by role
        $adminCount = $users->where('role', 'ADMIN')->count();
        $staffCount = $users->where('role', 'STAFF')->count();
        $customerCount = $users->where('role', 'CUSTOMER')->count();

        $html = '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Users Report | Profit Gym Tone</title>
            <link rel="icon" type="image/png" href="' . asset('images/header/favicon.png') . '">
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="' . asset('css/print.css') . '">
            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(function() {
                        window.close();
                    }, 1000);
                };
            </script>
        </head>
        <body>
            <div class="document">
                 <div class="header">
                    <img src="' . asset('logos/profit-gym.png') . '" alt="Company Logo" class="header-logo">
                    <p>jeremiahpanganibanr@gmail.com | +63 912 123 6182</p>
                </div>

                <h2 class="report-title">USERS REPORT</h2>

                <div class="summary-box">
                    <div class="summary-item">
                        <div class="summary-count">' . $users->count() . '</div>
                        <div>Total Users</div>
                    </div>
                    <div class="summary-item">
                        <div class="summary-count">' . $adminCount . '</div>
                        <div>Admins</div>
                    </div>
                    <div class="summary-item">
                        <div class="summary-count">' . $staffCount . '</div>
                        <div>Staff</div>
                    </div>
                    <div class="summary-item">
                        <div class="summary-count">' . $customerCount . '</div>
                        <div>Customers</div>
                    </div>
                </div>

                <table>
                    <thead>
                        <tr>
                            <th>Photo</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>Role</th>
                            <th>Created At</th>
                        </tr>
                    </thead>
                    <tbody>';

        foreach ($users as $user) {
            $roleBadge = match ($user->role) {
                'ADMIN' => '<span class="badge badge-admin">ADMIN</span>',
                'STAFF' => '<span class="badge badge-staff">STAFF</span>',
                'CUSTOMER' => '<span class="badge badge-customer">CUSTOMER</span>',
                default => '<span class="badge">' . $user->role . '</span>',
            };

            $photoHtml = $user->photo 
                ? '<img src="' . asset('storage/' . $user->photo) . '" class="user-photo">'
                : '<div class="user-photo" style="background:#eee;display:flex;align-items:center;justify-content:center;">' 
                  . substr($user->first_name, 0, 1) . substr($user->last_name, 0, 1) . '</div>';

            $html .= '<tr>
                <td>' . $photoHtml . '</td>
                <td>' . htmlspecialchars($user->first_name) . '</td>
                <td>' . htmlspecialchars($user->last_name) . '</td>
                <td>' . htmlspecialchars($user->email) . '</td>
                <td>' . ($user->phone_number ?? 'N/A') . '</td>
                <td>' . ($user->address ?? 'N/A') . '</td>
                <td>' . $roleBadge . '</td>
                <td class="date">' . $user->created_at->format('M j, Y') . '</td>
            </tr>';
        }

        $html .= '</tbody>
                </table>

                <div class="footer">
                    <p>Generated by ' . $printedBy . ' on ' . $printedAt . '</p>
                    <p>Confidential Document • © ' . date('Y') . ' Profit Gym Tone Management</p>
                </div>
            </div>
        </body>
        </html>';

        return response($html);
    }
}