<?php

namespace App\Http\Controllers;

use App\Models\UserMembership;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;

class UserMembershipController extends Controller
{
    public function index()
    {
        return view('pages.usermembership');
    }

    public function printAllDataUserMembership()
    {
        $userMemberships = UserMembership::with(['user', 'membership', 'payments'])->get();

        $user = auth()->user();
        $printedBy = $user ? htmlspecialchars($user->name) : 'Guest';
        $printedAt = now()->format('F j, Y \a\t g:i A');

        $html = '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Enrolled Memberships Report | Profit Gym Tone</title>
            <link rel="icon" type="image/png" href="' . asset('images/header/favicon.png') . '">
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="' . asset('css/print.css') . '">
            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(function() {
                        window.close();
                    }, 1000);
                };
            </script>
        </head>
        <body>
            <div class="document">
                <div class="header">
                    <img src="' . asset('logos/profit-gym.png') . '" alt="Company Logo" class="header-logo">
                    <p>jeremiahpanganibanr@gmail.com | +63 912 123 6182</p>
                </div>
                <h2 class="report-title">ENROLLED MEMBERSHIPS REPORT</h2>

                <table>
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Membership</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Status</th>
                            <th>Date Submitted</th>
                        </tr>
                    </thead>
                    <tbody>';

        foreach ($userMemberships as $membership) {
            $statusBadge = match ($membership->status) {
                'PENDING' => '<span class="badge pending">PENDING</span>',
                'APPROVED' => '<span class="badge approved">APPROVED</span>',
                'REJECTED' => '<span class="badge rejected">REJECTED</span>',
                default => '<span class="badge">' . $membership->status . '</span>',
            };

            $html .= '<tr>
                <td>' . ($membership->user->name ?? 'N/A') . '</td>
                <td>' . ($membership->membership->name ?? 'N/A') . '</td>
                <td class="date">' . Carbon::parse($membership->start_date)->format('M j, Y') . '</td>
                <td class="date">' . Carbon::parse($membership->end_date)->format('M j, Y') . '</td>
                <td>' . $statusBadge . '</td>
                <td class="date">' . $membership->created_at->format('M j, Y g:i A') . '</td>
            </tr>';
        }

        $html .= '</tbody>
                </table>

                <div class="footer">
                    <p>Generated by ' . $printedBy . ' on ' . $printedAt . '</p>
                    <p>Confidential Document • © ' . date('Y') . ' Profit Gym Management</p>
                </div>
            </div>
        </body>
        </html>';

        return response($html);
    }
}